### ISSUE TITLE
Token Name

### ISSUE THREAD

**Issue by lolobu12** [atomone-hub/genesis#68] opened 2023-12-08 09:46 UTC
Hi community,

looking at the foundation of what AtomOne shall be, also in relation with #41  Photon Token design, I propose to not name the new token ATOM1.
Instead my suggestion would be #GAIA to relate to the core ideas which would also reflect the reasoning of the fork.
#HUB would also be a possibility I prefer over #ATOM1.

The similarity with the Atom to Atom1 token would not only always remember of the fork character, which will  also carry a level of tensions, it also shows less independence. To restart and find an own identity it would be an advantage to have no similar token ticker.
Also, there is the aspect of purchasing the token and understand the ecosystem for less involved investors or somebody researching info about AtomOne. 
A more distinguished brand from the Cosmos Atom token is neccesary to be independent; also to ensure its identity in speech, merch, public relation etc.

On the back of this token discussion you could also discuss if the whole project in this case could be names #Gaia or #Hub but that would be a follow-up decission.
Though I understand Jaes sentiment to relate to the core of his former project Cosmos Hub with #Atom I believe a further step away to ensure the resturn to the core ideas of the hub+ photon is required to ensure a well done split as intended.

Regards.

**Comment by jaekwon** [comment] 2023-12-08 09:57
This is a duplicate of #63. I'll leave the other one open. Please contribute to the discussion there.

**Closed by jaekwon** 2023-12-08 09:57 UTC
