### ISSUE TITLE
Atomone equai airdrop to ones who voted no with veto or no on last governance which qualified for GNOLAND  and for those who did not vote but got overwritten by validators vote

### ISSUE THREAD

**Issue by tintin2828** [atomone-hub/genesis#43] opened 2023-12-02 00:45 UTC
Just want to call out that Atomone airdrop to 
1. No with veto or veto to last proposal where users qualified for GNOLAND 
2. Those who did not vote and their vote got overwritten by validators yes vote. A lot of users did not have visibility on Jae messaging for this vote. If I had seen Jae reasoning I would have voted no or no with veto

**Comment by giunatale** [comment] 2023-12-02 00:58
discussion around this is being held in #12, this is a duplicate.

plus, unfortunately, I disagree with 2 as I believe most others will do. And most of us agree we should exclude prop 69 for the very reason you are stated in 1.

**Comment by jaekwon** [comment] 2023-12-02 01:37
But it looks like the air-drop will include YES voters (they just won't get the large 2x reward on top of the default).

**Comment by jaekwon** [comment] 2023-12-02 01:39
Closing because this is a duplicate of this issue: https://github.com/atomone-hub/genesis/issues/12#issuecomment-1831327478

**Closed as completed by jaekwon** 2023-12-02 01:39 UTC
Labels: tokenomics
